# crf条件随机场TF2.0实现

In [4]:
import tensorflow_addons as tfa
import tensorflow as tf
import numpy as np

In [6]:
inputs  =tf.random.truncated_normal([2,10,5])
target = tf.convert_to_tensor(np.random.randint(5,size=(2,10)),dtype=tf.int32)
print('inputs',inputs)
print('target',target)

inputs tf.Tensor(
[[[-0.24237518  1.2641362   1.3636712   1.8167077  -0.33303598]
  [-0.1470257   1.8658403  -0.15868032  0.3246955   0.73701763]
  [-0.9393096   1.2122188  -0.35139388  0.12431969 -1.2325217 ]
  [ 0.14628626 -1.4642243   1.468464    1.2341481   1.7579855 ]
  [ 0.0264452   0.5828828  -0.7979244   1.2174355   0.6484906 ]
  [ 1.5755994  -0.13536716  0.08630986  0.5481468  -1.3100848 ]
  [ 0.37212893 -0.4761124  -0.72802234  0.33704305 -0.72596633]
  [ 0.19393633 -1.6006052   1.7110336   0.03406042  1.4534571 ]
  [-0.45074388 -0.9721942   0.12382977 -0.6720943  -0.1184278 ]
  [-0.7670066  -0.04397529 -0.5679411  -0.22970252  0.37673706]]

 [[ 1.3064348   0.30537656 -0.5313072  -1.7366171   0.9162978 ]
  [ 1.0832168  -0.56690544  1.6693429   0.80721164 -0.8886017 ]
  [-0.7115253  -0.13968538 -0.11179686  0.33724812  0.29803425]
  [ 1.2274717  -1.15741    -0.00691201 -0.62221175 -0.33944866]
  [-0.6943355   0.38990042  0.76180094 -0.57023096  1.1261048 ]
  [ 0.79076797 -0.34

In [7]:
out = tf.keras.layers.Softmax(inputs)
print('out',out)
lens = tf.convert_to_tensor([9,6],dtype=tf.int32)
print('lens',lens)

out <tensorflow.python.keras.layers.advanced_activations.Softmax object at 0x000002746CF1C4E0>
lens tf.Tensor([9 6], shape=(2,), dtype=int32)


In [8]:
log_likelihood,tran_paras = tfa.text.crf_log_likelihood(inputs,target,lens)
print('log_likelihood',log_likelihood)
print('tran_paras',tran_paras)
batch_pred_sequence,batch_viterbi_score = tfa.text.crf_decode(inputs,tran_paras,lens)
print('batch_pred_sequence',batch_pred_sequence)
print('batch_viterbi_score',batch_viterbi_score)

log_likelihood tf.Tensor([-16.168137 -13.354148], shape=(2,), dtype=float32)
tran_paras <tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 0.6348388 , -0.25576293, -0.6192871 , -0.0603593 ,  0.11227125],
       [ 0.68271875, -0.11100715,  0.3013221 ,  0.08545876, -0.5414578 ],
       [-0.06528264,  0.4829855 ,  0.4328134 ,  0.6456187 ,  0.5721227 ],
       [-0.15964991,  0.46252346, -0.07468534, -0.36722586, -0.23964864],
       [-0.11715508,  0.6361717 , -0.77281106, -0.21178311, -0.2206111 ]],
      dtype=float32)>
batch_pred_sequence tf.Tensor(
[[3 1 1 2 1 0 0 2 2 2]
 [0 0 0 0 4 0 4 4 4 4]], shape=(2, 10), dtype=int32)
batch_viterbi_score tf.Tensor([12.995613   6.7221036], shape=(2,), dtype=float32)


In [9]:
loss = tf.reduce_sum(-log_likelihood)
print('loss',loss)

loss tf.Tensor(29.522285, shape=(), dtype=float32)
